In [1]:
# Initial setup
import pandas as pd

print("Setup complete!")

Setup complete!

In [2]:
# Kodblock för att förstå och sen kunna filtrera datasettet.
df = pd.read_csv("RAW_recipes.csv")
df.head(10)
df.describe()
df.columns
# df.shape
# df.head(5)

Index(['name', 'id', 'minutes', 'contributor_id', 'submitted', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'ingredients',
       'n_ingredients'],
      dtype='object')

In [9]:
# Rensar upp i datasettet.
columns_to_use = ['id', 'name', 'minutes', 'n_steps', 'steps', 'ingredients', 'n_ingredients']

df = pd.read_csv("RAW_recipes.csv", usecols=columns_to_use, skipinitialspace=True)
df = df.dropna()
df['name'].str.strip()

# df.to_csv("Data.csv")

df2 = df.head(10)

df2.to_csv("data2.csv")
df.head(11)

,name,id,minutes,n_steps,steps,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,11,"['make a choice and proceed with recipe', 'dep...","['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,9,"['preheat oven to 425 degrees f', 'press dough...","['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,6,"['brown ground beef in large pot', 'add choppe...","['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,11,['place potatoes in a large pot of lightly sal...,"['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,5,['mix all ingredients& boil for 2 1 / 2 hours ...,"['tomato juice', 'apple cider vinegar', 'sugar...",8
5,apple a day milk shake,5289,0,4,"['combine ingredients in blender', 'cover and ...","['milk', 'vanilla ice cream', 'frozen apple ju...",4
6,aww marinated olives,25274,15,4,['toast the fennel seeds and lightly crush the...,"['fennel seeds', 'green olives', 'ripe olives'...",9
7,backyard style barbecued ribs,67888,120,10,['in a medium saucepan combine all the ingredi...,"['pork spareribs', 'soy sauce', 'fresh garlic'...",22
8,bananas 4 ice cream pie,70971,180,8,"['crumble cookies into a 9-inch pie plate , or...","['chocolate sandwich style cookies', 'chocolat...",6
9,beat this banana bread,75452,70,12,"['preheat oven to 350 degrees', 'butter two 9x...","['sugar', 'unsalted butter', 'bananas', 'eggs'...",9
10,berry good sandwich spread,109439,5,2,"['in medium size bowl , coarsely mash cranberr...","['whole berry cranberry sauce', 'sour cream', ...",3

In [4]:
# Skapar en databas av den nya .csv filen.
import sqlite3

conn = sqlite3.connect('Database.db')

df.to_sql('Data_table', conn, if_exists='replace', index=False)

conn.close()

In [7]:
print(len(df))

df2.head(100)

231636

,name,id,minutes,n_steps,steps,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,11,"['make a choice and proceed with recipe', 'dep...","['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,9,"['preheat oven to 425 degrees f', 'press dough...","['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,6,"['brown ground beef in large pot', 'add choppe...","['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,11,['place potatoes in a large pot of lightly sal...,"['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,5,['mix all ingredients& boil for 2 1 / 2 hours ...,"['tomato juice', 'apple cider vinegar', 'sugar...",8
5,apple a day milk shake,5289,0,4,"['combine ingredients in blender', 'cover and ...","['milk', 'vanilla ice cream', 'frozen apple ju...",4
6,aww marinated olives,25274,15,4,['toast the fennel seeds and lightly crush the...,"['fennel seeds', 'green olives', 'ripe olives'...",9
7,backyard style barbecued ribs,67888,120,10,['in a medium saucepan combine all the ingredi...,"['pork spareribs', 'soy sauce', 'fresh garlic'...",22
8,bananas 4 ice cream pie,70971,180,8,"['crumble cookies into a 9-inch pie plate , or...","['chocolate sandwich style cookies', 'chocolat...",6
9,beat this banana bread,75452,70,12,"['preheat oven to 350 degrees', 'butter two 9x...","['sugar', 'unsalted butter', 'bananas', 'eggs'...",9